In [3]:
from math import *
import numpy as np
import sympy as sy
from sympy import *

In [4]:
#自定义函数部分
def m(a):
    return np.linalg.norm(a)

def n(a):
    return a/m(a)

def proj(a,b):
    return b/np.linalg.norm(b)*(a*b/np.linalg.norm(b))

def comp(a,b):
    return a-proj(a,b)

def convert(a):
    n=a.shape
    n=n[0]
    b=np.zeros(n)
    for i in range(n):
        b[i]=float(a[i])
    return b
    
#test data
a=np.array([1,2,0])
b=np.array([1,0,0])
print(proj(a,b),comp(a,b))

a=Matrix([1,2,3])
b=Matrix([2,4,3])
a=convert(a)
b=convert(b)
print(a,b)
comp(a,b)

[1. 0. 0.] [0. 2. 0.]
[1. 2. 3.] [2. 4. 3.]


array([0.86206897, 0.89655172, 2.06896552])